name: Run node application tests

on:
  workflow_call:
    inputs:
      workspace:
        required: false
        type: string
    secrets:
      gh_package_registry_token:
        required: true

jobs:
  node_test:
    name: Run node application tests
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.gh_package_registry_token }}

    services:
        postgres:
            image: postgis/postgis:16-3.4-alpine
            env:
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: postgres
                POSTGRES_DB: safeguard-test-api
            ports:
                - 5432:5432
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://npm.pkg.github.com/"
          scope: "@safeguardapp"

      - name: Create api schema
        run: psql postgresql://postgres:postgres@localhost:5432/safeguard-test-api -c "CREATE SCHEMA IF NOT EXISTS api;"

      - name: Install node packages
        run: npm ci --force

      - name: Run test command
        if: "${{ inputs.workspace == '' }}"
        run: npm run test

      - name: Run test command in workspace ${{ inputs.workspace }}
        if: "${{ inputs.workspace != '' }}"
        run: npm run test -w ${{ inputs.workspace }}
