name: Test node application build

on:
  workflow_call:
    secrets:
      token:
        required: true
      gh_package_registry_token:
        required: true

jobs:
  node_build:
    name: Test node application build
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.gh_package_registry_token }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.token }}

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: "https://npm.pkg.github.com/"
          scope: "@safeguardapp"

      - name: Install node packages
        run: npm ci

      - name: Run build command
        run: npm run build
