name: Run node application tests

on:
  workflow_call:
    inputs:
      workspace:
        required: false
        type: string
    secrets:
      gh_package_registry_token:
        required: true

jobs:
  node_test:
    name: Run node application tests
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.gh_package_registry_token }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://npm.pkg.github.com/"
          scope: "@safeguardapp"

      - name: Install node packages
        run: npm ci --force

      - name: Run test command
        if: "${{ inputs.workspace == '' }}"
        run: npm run test

      - name: Run test command in workspace ${{ inputs.workspace }}
        if: "${{ inputs.workspace != '' }}"
        run: npm run test -w ${{ inputs.workspace }}
